apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-k8s-app
  template:
    metadata:
      labels:
        app: mongo-k8s-app
    spec:
      containers:
      - name: app
        image: mongo-k8s-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        - name: MONGO_HOST
          value: mongodb-service
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_DB
          value: testdb
